### ISSUE TITLE
Game crash start

### ISSUE THREAD

**Issue by Mozork01** [Globox1997/LibZ#2]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.25

### Mod Version

Libz-1.0.3

### Describe the Issue

The game crashes on startup with adaptative tooltip mod

### latest.log

A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'adaptive-tooltips'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'adaptive-tooltips'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	... 2 more
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'preLaunch' provided by 'adaptive-tooltips'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
	... 3 more
Caused by: java.lang.RuntimeException: Mixin transformation of com.llamalad7.mixinextras.MixinExtrasBootstrap failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 4 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [libz.mixins.json:config.AutoConfigAccess from mod libz] from phase [DEFAULT] in config [libz.mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 13 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: libz.mixins.json:config.AutoConfigAccess from mod libz target me.shedaniel.autoconfig.AutoConfig was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:948)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:882)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)
	... 19 more

**Comment by NotNeonite** [comment]
Having this issue too, doesn't seem like it's directly connected to adaptative tooltips, but rather LibZ.

"Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [libz.mixins.json:config.AutoConfigAccess from mod libz] from phase [DEFAULT] in config [libz.mixins.json] **FAILED during PREPARE**"

I've been trying to fix this myself, if you find any solutions then I'd love to know.

**Comment by Globox1997** [comment]
How can I reproduce this bug?

**Comment by Linguardium** [comment]
make a dummy mod that loads autoconfig in a mixin config plugin's onLoad
your AutoConfigAccess mixin will fail to apply

**Comment by Globox1997** [comment]
thanks, any solution for this @Linguardium ?

**Comment by Linguardium** [comment]
https://gist.github.com/Linguardium/7ccc785f94d19465a13fd1f9b29ed450

this works. it isnt pretty. A better option may be to contact shedaniel and see if they will add an api or something for syncing configs

**Comment by dudematthew** [comment]
### Update: Doesn't work, just moves the error to the world loading

Yeah, headache.

The problem is that LevelZ or one of its addons loads the AutoConfig class in its initializer before LibZ has a chance to apply a mixin to it.

Since the integration is optional, the fix is to edit `libz.mixins.json` inside the .jar
Remove "plugin": "net.libz.mixin.LibzMixinPlugin" line and leave mixins empty.

```json
libz.mixins.json for v1.1.0
{
  "required": true,
  "minVersion": "0.8",
  "package": "net.libz.mixin",
  "compatibilityLevel": "JAVA_21",
  "mixins": [],
  "client": [
    "client.InventoryScreenMixin",
    "client.HandledScreenMixin",
    "client.IntegratedServerLoaderMixin",
    "client.MouseMixin"
  ],
  "injectors": {
    "defaultRequire": 1
  },
  "refmap": "libz-refmap.json"
}
```

@Globox1997

**Comment by dudematthew** [comment]
@Globox1997 could you please fix this issue? I can't really use the levelZ at all in my modpack which is sad considering how cool it is

```log
A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'debugify' at 'com.llamalad7.mixinextras.MixinExtrasBootstrap::init'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:158)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:66)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'debugify' at 'com.llamalad7.mixinextras.MixinExtrasBootstrap::init'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$0(FabricLoaderImpl.java:409)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:407)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:156)
	... 5 more
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'preLaunch' provided by 'debugify'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:405)
	... 6 more
Caused by: java.lang.RuntimeException: Mixin transformation of com.llamalad7.mixinextras.MixinExtrasBootstrap failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:440)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:336)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:231)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 7 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [libz.mixins.json:config.AutoConfigAccess from mod libz] from phase [DEFAULT] in config [libz.mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:685)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:632)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:590)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:509)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:485)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.lockAndSelect(MixinProcessor.java:437)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.couldTransformClass(MixinProcessor.java:397)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.couldTransformClass(MixinTransformer.java:265)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:233)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:435)
	... 17 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: libz.mixins.json:config.AutoConfigAccess from mod libz target me.shedaniel.autoconfig.AutoConfig was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:973)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:903)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:933)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:858)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:587)
	... 25 more
```

https://mclo.gs/8KJ7Yxi

**Comment by dudematthew** [comment]
Hey, would it theoretically work if you replaced the `AutoConfigAccess` mixin with plain reflection instead?

The crash in issue #2 happens because `me.shedaniel.autoconfig.AutoConfig` gets loaded too early by other mods (like adaptive-tooltips in their `preLaunch` entrypoint), so by the time the mixin subsystem tries to prepare `AutoConfigAccess`, the class is already in memory and can't be transformed anymore.

Since `AutoConfigAccess` only exists to read the private `holders` field from `AutoConfig`, and that field is only accessed at runtime (in `EventInit` and `LibzClientPacket`, both well after startup), the mixin isn't really buying anything over simple reflection:

```java
private static Field holdersField;

@SuppressWarnings("unchecked")
public static Map<Class<? extends ConfigData>, ConfigHolder<?>> getHolders() {
    try {
        if (holdersField == null) {
            holdersField = AutoConfig.class.getDeclaredField("holders");
            holdersField.setAccessible(true);
        }
        return (Map<Class<? extends ConfigData>, ConfigHolder<?>>) holdersField.get(null);
    } catch (ReflectiveOperationException e) {
        throw new RuntimeException("Failed to access AutoConfig.holders", e);
    }
}
```

Also worth noting — removing `config.AutoConfigAccess` from `libz.mixins.json` alone isn't enough. The `"plugin": "net.libz.mixin.LibzMixinPlugin"` entry also needs to go, otherwise the crash can still occur through `MarshallerImplMixin` triggering class loading of neighbouring cloth-config classes. The plugin itself is all no-ops anyway so removing it from the JSON should be completely safe.

Just wondering if you've considered this approach or if there's a reason the mixin was preferred over reflection!

**Comment by dudematthew** [comment]
All right, so I made a push request that fixes this issue but since it's not a 100% clean fix, I'll leave the .jar in case someone wants to get it. 

https://hostforever.org/uploads/1779022529500-fee4d4c9f02b9006-libz-1.1.0%20_loaded%20too%20early%20fix_.jar

**Comment by Globox1997** [comment]
mh I understand the issue. reflection might be a solution for the holders field.
I wonder who wants to read a config during the mixin process, just automate it or create your own config reader :D
the main problem would be the MarshallerImplMixin cause it is used to distinguish between client and server settings, not just visuals.
Another solution would be setting the required field to false I guess :D but there is no good solution imo.
